theme: jekyll-theme-minimal
title: Sebastian's Portfolio
description: Currently being rebuilt after loss of website. Previously sebetteportfolio.com

layout: post
title: "Welcome"
date: YYYY-MM-DD hh:mm:ss -0000
categories: CATEGORY-1 CATEGORY-2
